version: '3'
networks:
  internal:
    driver: bridge
  external:
    driver: bridge
services:
  app:
    build: .
    networks:
      internal:
        aliases:
          - app
  proxy:
    restart: on-failure
    image: nginx:1.15.5-alpine
    volumes: ['./proxy/default.conf:/etc/nginx/conf.d/default.conf']
    ports: ['8080:8080']
    networks:
      internal:
        aliases: []
      external:
        aliases: []
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:8080/ || exit 1
      timeout: 1s
      retries: 99